---
title: "Dzisiejszy ruch na stronie"
runtime: shiny
output: 
  html_document: 
    fig_height: 8
    fig_width: 12
    self_contained: yes
---

```{r document_setup, echo=FALSE, message=FALSE, error=FALSE, warning=FALSE}
client_secret <- "wstaw_swoje"
client_id <- "wstaw_swoje"

# dla poprawnej obsługi pl literek - m.in. sortowanie
Sys.setlocale("LC_CTYPE", "pl_PL.UTF-8") -> dev_nul

delta <- 1

library(tidyverse)
library(knitr)
library(kableExtra)

# chunks options
opts_chunk$set(
   message = FALSE,
   error = FALSE,
   warning = FALSE,
   echo = FALSE
)
options(knitr.table.format = "html")


library(tidyverse)
library(lubridate)
library(forcats)
library(stringr)
library(plotly)

# devtools::install_github("Tatvic/RGoogleAnalytics")
library(RGoogleAnalytics)

# prokulski@gmail.com
oauth_token <- Auth(
   client.id = client_id,
   client.secret = client_secret
)


ValidateToken(oauth_token)

# Dimensions & Metrics
# https://developers.google.com/analytics/devguides/reporting/core/dimsmets

# dane do dzisiaj, z ostaniego tygodnia
query.list <- Init(
   start.date = as.character(Sys.Date() - 2),
   end.date = as.character(Sys.Date()),
   dimensions = "ga:date,ga:hour,ga:pageTitle,ga:PagePath,ga:source,ga:fullReferrer",
   # up to 7
   metrics = "ga:pageviews",
   # ,ga:uniquePageviews,ga:timeOnPage,ga:entrances,ga:exits", # up to 10
   max.results = 20000,
   table.id = "ga:7093365"
) # id strony? 7093365 = prokulski.net

ga.query <- QueryBuilder(query.list)
ga.data <- GetReportData(ga.query, oauth_token)

# daty w normalnym stylu :)
ga.data$date <- ymd(ga.data$date)
ga.data$datetime <-
   make_datetime(
      year(ga.data$date),
      month(ga.data$date),
      day(ga.data$date),
      as.numeric(ga.data$hour)
   )



# poprawienie tytyłów i urli stron
ga_data_corr <- ga.data %>%
   # filter(date >= today() - days(3)) %>%
   mutate(pagePath = gsub("/comment-page-[0-9]*/", "/", PagePath)) %>%
   mutate(pagePath = if_else(
      pagePath == "/index.php",
      "/",
      gsub("/index.php", "", pagePath, fixed = TRUE)
   )) %>%
   # ujednolicenie source
   mutate(source = if_else(grepl("facebook.com", source), "facebook.com", source)) %>%
   mutate(source = if_else(grepl("messenger.com", source), "facebook.com", source)) %>%
   mutate(source = if_else(grepl("lnkd.in", source), "linkedin.com", source))
```


### Najpopulaniejsze strony i żródła wizyt


```{r}
ga_data_corr %>%
   filter(date >= Sys.Date() - delta) %>%
   group_by(pagePath, source) %>%
   summarize(pageviews_total = sum(pageviews)) %>%
   ungroup() %>%
   group_by(pagePath) %>%
   mutate(pageviews_total_page = sum(pageviews_total)) %>%
   ungroup() %>%
   filter(pageviews_total_page >= quantile(pageviews_total_page, 0.5)) %>%
   mutate(pagePath = str_sub(pagePath, -55, -1)) %>%
   ggplot() +
   geom_col(aes(pagePath, pageviews_total, fill = source)) +
   theme(legend.position = "bottom") +
   coord_flip()
```

```{r}
ga_data_corr %>%
   filter(date >= Sys.Date() - delta) %>%
   group_by(pagePath, source) %>%
   summarize(pageviews_total = sum(pageviews)) %>%
   ungroup() %>%
   group_by(pagePath) %>%
   mutate(pageviews_total_page = sum(pageviews_total)) %>%
   ungroup() %>%
   filter(pageviews_total_page >= quantile(pageviews_total_page, 0.75)) %>%
   mutate(pagePath = str_sub(pagePath, -55, -1)) %>%
   plot_ly(
      type = "bar",
      x = ~pageviews_total,
      y = ~pagePath,
      color = ~source,
      text = ~ paste0(
         "Path: ",
         pagePath,
         "<br>",
         "Source: ",
         source,
         "<br>",
         "PV: ",
         pageviews_total
      ),
      hoverinfo = "text",
      showlegend = FALSE
   ) %>%
   layout(barmode = "stack")
```


### Najpopularniejsze strony - pagePath vs PV


```{r}
ga_data_corr %>%
   filter(date >= Sys.Date() - delta) %>%
   group_by(pagePath) %>%
   summarise(PV = sum(pageviews)) %>%
   ungroup() %>%
   filter(PV > quantile(PV, 0.75)) %>%
   arrange(PV) %>%
   mutate(pagePath = str_sub(pagePath, -55, -1)) %>%
   mutate(pagePath = fct_inorder(pagePath)) %>%
   ggplot() +
   geom_col(aes(pagePath, PV), fill = "lightblue") +
   coord_flip()
```

```{r eval=FALSE}
ga_data_corr %>%
   filter(date >= Sys.Date() - delta) %>%
   group_by(pagePath) %>%
   summarise(PV = sum(pageviews)) %>%
   ungroup() %>%
   filter(PV > quantile(PV, 0.75)) %>%
   arrange(PV) %>%
   mutate(pagePath = str_sub(pagePath, -55, -1)) %>%
   mutate(pagePath = fct_inorder(pagePath)) %>%
   plot_ly(
      type = "bar",
      x = ~PV,
      y = ~pagePath,
      text = ~ paste0(
         "Path: ", pagePath, "<br>",
         "PV: ", PV
      ),
      hoverinfo = "text",
      showlegend = FALSE
   )
```

### Źródła - source vs PV

```{r}
ga_data_corr %>%
   filter(date >= Sys.Date() - delta) %>%
   group_by(source) %>%
   summarise(PV = sum(pageviews)) %>%
   ungroup() %>%
   arrange(PV) %>%
   mutate(source = fct_inorder(source)) %>%
   ggplot() +
   geom_col(aes(source, PV)) +
   coord_flip()
```

```{r eval=FALSE}
ga_data_corr %>%
   filter(date >= Sys.Date() - delta) %>%
   group_by(source) %>%
   summarise(PV = sum(pageviews)) %>%
   ungroup() %>%
   arrange(PV) %>%
   mutate(source = fct_inorder(source)) %>%
   plot_ly(
      type = "bar",
      x = ~PV,
      y = ~source,
      text = ~ paste0(
         "Source: ", source, "<br>",
         "PV: ", PV
      ),
      hoverinfo = "text",
      showlegend = FALSE
   )
```

### Ruch na stronach ze źródeł - pagePath vs source

```{r}
ga_data_corr %>%
   filter(date >= Sys.Date() - delta) %>%
   group_by(source, pagePath) %>%
   summarise(PV = sum(pageviews)) %>%
   ungroup() %>%
   mutate(PV_p = 100 * PV / sum(PV)) %>%
   filter(PV_p >= quantile(PV_p, 0.75)) %>%
   mutate(pagePath = str_sub(pagePath, -55, -1)) %>%
   ggplot() +
   geom_tile(aes(source, pagePath, fill = PV),
      color = "gray50",
      show.legend = FALSE
   ) +
   geom_text(aes(source, pagePath, label = sprintf("%.1f%%", PV_p))) +
   scale_fill_distiller(palette = "YlOrRd") +
   theme(axis.text.x = element_text(
      angle = 90,
      vjust = 0,
      hjust = 1
   ))
```

```{r}
ga_data_corr %>%
   filter(date >= Sys.Date() - delta) %>%
   group_by(source, pagePath) %>%
   summarise(PV = sum(pageviews)) %>%
   ungroup() %>%
   mutate(PV_p = 100 * PV / sum(PV)) %>%
   filter(PV_p >= quantile(PV_p, 0.75)) %>%
   arrange(desc(PV_p)) %>%
   mutate(PV_p = round(PV_p, 2)) %>%
   head(20) %>%
   kable("html") %>%
   kable_styling()
```


### Ruch w ciągu dnia total - datetime vs PV


```{r}
ga_data_corr %>%
   filter(date >= Sys.Date() - delta) %>%
   group_by(datetime) %>%
   summarise(PV = sum(pageviews)) %>%
   ungroup() %>%
   ggplot() +
   geom_col(aes(datetime, PV), fill = "lightgreen", color = "gray50")
```


### Ruch w ciągu dnia - żródła


```{r}
ga_data_corr %>%
   filter(date >= Sys.Date() - delta) %>%
   group_by(source, datetime) %>%
   summarise(PV = sum(pageviews)) %>%
   ungroup() %>%
   filter(PV > 1) %>%
   arrange(desc(PV)) %>%
   mutate(source = fct_inorder(source)) %>%
   ggplot() +
   geom_col(aes(datetime, PV, fill = source), show.legend = FALSE) +
   facet_wrap(~source)
```


### Ruch w ciągu dnia - strony wg żródła


```{r}
ga_data_corr %>%
   filter(date >= Sys.Date() - delta) %>%
   filter(substr(pagePath, 0, 10) != "/outgoing/") %>%
   mutate(pagePath = if_else(
      str_sub(pagePath, 1, 3) == "/20",
      str_sub(pagePath, 13, -1),
      pagePath
   )) %>%
   group_by(source, pagePath, datetime) %>%
   summarise(PV = sum(pageviews)) %>%
   ungroup() %>%
   filter(PV > 1) %>%
   ggplot() +
   geom_col(aes(datetime, PV, fill = source)) +
   facet_wrap(~pagePath) +
   theme(legend.position = "bottom")
```
